### ISSUE TITLE
Need to add the network checking before any auth request

### ISSUE THREAD

**Issue by heidijinxujia** [AzureAD/microsoft-authentication-library-common-for-android#275]

**Comment by alfetch** [comment]
Hi.. Is it possible this can be fixed in the 'com.microsoft.identity.client:msal:0.2.2' ?
'com.microsoft.identity.client:msal:0.2.1' has this error. 
A fix could be this instead of using getEntry? 

https://stackoverflow.com/questions/52024752/android-p-keystore-exception-android-os-servicespecificexception

**Comment by iambmelt** [comment]
@heidijinxujia @kreedula I suspect this is probably implemented already - can we close?
