### ISSUE TITLE
The WebView should not load multiple times in a fragment's lifecycle.

### ISSUE THREAD

**Issue by arislomovic** [AzureAD/microsoft-authentication-library-common-for-android#799]
The WebView loadUrl function is called in onStart(), which means any time the app is placed in the background and brought to the front again, the state of the webview is lost and the webview re-loads the url.

**Comment by wmiranda** [comment]
Hi @shoatman !
Could you please check this one out?
It's a major issue since every time the user sends the app to the background, when getting back, all his progress in the B2C journeys is lost.
For instance, if a user goes to check his messages for an OTP verification, when he comes back to the app to insert the code, he will have to start all over again. A painful loop.
Thank you in advance!

**Comment by rpdome** [comment]
Fixed in #809
